### ISSUE TITLE
cannot create directory ‘/usr/share/dotnet’: Permission denied

### ISSUE THREAD

**Issue by HGGamers** [vegardit/docker-gitea-act-runner#12]
I am currently trying to get a .net console application built. 
Unfortunately it can't install .net because it doesn't have permissions to create the folder. Here is the error message:

```
[command]/run/act/actions/https---github.com-actions-setup-dotnet@v3/externals/install-dotnet.sh --channel 7.0
mkdir: cannot create directory ‘/usr/share/dotnet’: Permission denied
::error::Failed to install dotnet, exit code: 1. mkdir: cannot create directory ‘/usr/share/dotnet’: Permission denied%0A
```

Here is the workflow file:
```
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: https://github.com/actions/checkout@v3
    - name: Setup .NET
      uses: https://github.com/actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload a Build Artifact
      uses: https://github.com/actions/upload-artifact@v3.1.2
      with:
       name: Release 
       path: ./TestApplication/TestApplication/bin/Debug/net7.0/
       if-no-files-found: error
       retention-days: 90
```

Here is the Docker Compose part:
```
  gitea_act_runner:
    image: vegardit/gitea-act-runner:latest
    restart: unless-stopped
    container_name: gitearunner
    depends_on:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./gitea-builder:/data:rw
    environment:
      - TZ=Europe/Berlin
      - GITEA_INSTANCE_URL=XXXX
      - GITEA_RUNNER_REGISTRATION_TOKEN=XXXXX
```

Am I missing something obvious here that I still need to adjust?
