### ISSUE TITLE
Containers not cleaned up.

### ISSUE THREAD

**Issue by danielvandenberg95** [vegardit/docker-gitea-act-runner#15]
![image](https://github.com/vegardit/docker-gitea-act-runner/assets/8654023/7c1a7a68-cb69-40c3-a194-aa05a6d650dd)
After using this runner for a while, I'm seeing an excessive amount of containers, using up about 100Gb on my disk. I'm using a swarm stack with the following:

```yml
version: "3"

services:
  gitea_act_runner:
    image: vegardit/gitea-act-runner:latest

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /mnt/DockerData/gitea/runners/1:/data:rw # the config file is located at /data/.runner and needs to survive container restarts
    environment:
      TZ: "Europe/Berlin"
      # config parameters for initial runner registration:
      GITEA_INSTANCE_URL: myurl
```

My workflow is as follows:
```
name: Test and Build
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies as in yarn.lock
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn run jest
  Build:
    runs-on: ubuntu-latest
    needs: Run-Tests
    # Run the command build_and_push.sh
    steps:
    # Install docker-compose
      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - uses: actions/checkout@v2
      - name: Build and push
        run: sudo ./build_and_push.sh
```

where build_and_push.sh is the following:
```
#!/bin/bash
(for n in `seq 1 10`; do docker-compose build --parallel && break; done) && docker-compose push
```

I currently manually run ```docker container prune``` as a workaround.

Is this an issue with the docker wrapper, or with the act runner in general? If the second, I'll raise the issue there.
