### ISSUE TITLE
Error: daemon Docker Engine socket not found and docker_host config was invalid

### ISSUE THREAD

**Issue by xiaoxinpro** [vegardit/docker-gitea-act-runner#17]
Version:
```
gitea/act_runner:0.2.1
```

Docker-compose:

```
version: "3"

services:
  actrunner:
    image: gitea/act_runner:0.2.1
    container_name: actrunner
    restart: always
    volumes:
      - ./data/act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: 'Asia/Shanghai'
      CONFIG_FILE: '/data/config.yaml'
      GITEA_INSTANCE_URL: 'https://git.test.com'
      GITEA_RUNNER_REGISTRATION_TOKEN: '**********************************************'
```

Docker-compose Logs

```
actrunner  | time="2023-06-30T14:02:36Z" level=info msg="Starting runner daemon"
actrunner  | Error: daemon Docker Engine socket not found and docker_host config was invalid
actrunner  | time="2023-06-30T14:02:42Z" level=info msg="Starting runner daemon"
actrunner  | Error: daemon Docker Engine socket not found and docker_host config was invalid
```

**Comment by xiaoxinpro** [comment]
gitea/act runner:0.1.8 starts normally with the same configuration

**Comment by sebthom** [comment]
the docker image you are using is not related to this repository. please report your issue at https://gitea.com/gitea/act_runner/issues instead.

**Comment by 7IXKTUIV1** [comment]
I'm also getting the same error running:  `vegardit/gitea-act-runner:latest`

```
level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.1."
level=warning msg="Runner in user-mode."
level=warning msg="env GITEA_RUNNER_ENV_FILE has been ignored because config file is used"
level=info msg="Runner name is empty, use hostname '8f101f4eeae2'."
level=debug msg="Successfully pinged the Gitea instance server"
level=info msg="Runner registered successfully."
time="2023-07-02T07:14:44" level=info msg="Starting runner daemon"
Error: daemon Docker Engine socket not found and docker_host config was invalid
```

This is part of the docker-compose:
```
runner:
    image: vegardit/gitea-act-runner:latest
    container_name: gitea_runner
    depends_on:
      - giteaserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/gituser/docker/gitea/data/act_runner:/data:rw
    environment:
      - GITEA_INSTANCE_URL=http://192.168.1.150:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=****************************
```
