### ISSUE TITLE
How to run in the same docker network as gitea?

### ISSUE THREAD

**Issue by spamnick** [vegardit/docker-gitea-act-runner#24]
I have local gitea:
```
docker network create my-network

docker run --detach \
  --name=gitea \
  --publish 3000:3000 \
  --publish 2222:22 \
  --volume /home/nick/Dropbox/home-gitea:/data \
  --restart always \
  --network my-network \
  gitea/gitea:latest
```
And trying to run gitea-act-runner:
```
docker run \
    -e GITEA_INSTANCE_URL=http://172.20.0.2 \ #WHAT TO INSET HERE? gitea, gitea's docker IP or what?
    -e GITEA_RUNNER_REGISTRATION_TOKEN=<MYREGISTRATION_TOKEN> \
    -v /var/run/docker.sock:/var/run/docker.sock:rw \
    --name gitea_act_runner \
    --network my-network \
    vegardit/gitea-act-runner:latest
```

But errors:
```
level=error msg="Cannot ping the Gitea instance server" error="unavailable: dial tcp 172.20.0.2:80: connect: connection refused"
```

my-network is:
```
docker inspect my-network
[
    {
        "Name": "my-network",
        "Id": "13f388e7a3627a7d20f237e942141e6194b4099c7ee698a9299308c169e3051a",
        "Created": "2023-08-12T21:37:36.549950094+03:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "7439e13facaf3c20a2609ab942f30ca7b3c59cee128b2b5c7073548f1bf897f7": {
                "Name": "gitea",
                "EndpointID": "ad5469d1f7f55dd38a6a521baed268a6a2687df501957fb120ae0dab76718bf1",
                "MacAddress": "02:42:ac:14:00:02",
                "IPv4Address": "172.20.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

```

**Comment by sebthom** [comment]
does `gitea.my-network` work?

**Comment by prologic** [comment]
Some tips;

- You should really use DNS if you can
- Ideally run a Docker Swarm cluster
- Docker Swarm has built in DNS-based service discovery


Here's an example stack:

`gitea.yml`:

```yaml
---
version: "3.8"

services:
  server:
    image: gitea/gitea:1.20.2
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "2222:22/tcp"
    volumes:
      - gitea:/data
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.gitea.loadbalancer.server.port=3000"
        - "traefik.http.routers.gitea.rule=Host(`git.mydomain.tld`)"
      resources:
        reservations:
          cpus: "0.5"
          memory: 1280M
        limits:
          memory: 1664M
      restart_policy:
        condition: any

  runner:
    image: gitea/act_runner:nightly
    configs:
      - source: runner
        target: /config.yml
    environment:
      CONFIG_FILE: /config.yml
      GITEA_INSTANCE_URL: "https://git.mydomain.tld"
      GITEA_RUNNER_REGISTRATION_TOKEN: "xxx"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - runner:/data:rw
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
      restart_policy:
        condition: any

configs:
  runner:
    file: ./configs/runner.yml

networks:
  traefik:
    external: true

volumes:
  gitea:
    driver: local
  runner:
    driver: local
```

This is what I use to run my production Gitea + Gitea Actions Runner stack (_although I run 3 runners_). Deploy with:

```console
docker swarm init  # if not already
docker network create -d overlay traefik. # if not already
docker stack deploy -c gitea.yml gitea --with-registry-auth
```

What I haven't covered here is your Traefik/ingress setup. or DNS. I'll leave this as an exercise for you. Suffice to say, recommend you setup DNS and proper Ingres. You _can_ get away with internal DNS service discovery names too (_usually based on container/services names_).

**Comment by sebthom** [comment]
We are also using it with swarm stack named `gitea`, like this:

```yaml
version: '3.8'

networks:
  swarm_net:
    external: true
  stack_internal:
    attachable: false
    driver: overlay
    driver_opts:
      encrypted: "true"

services:

  service:
    image: gitea/gitea:1
    networks: [ stack_internal, swarm_net ]
    environment:
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ${STACK_DATA_ROOT}:/data:rw

  act_runner:
    image: vegardit/gitea-act-runner:latest
    networks:
      stack_internal:
      swarm_net:
        aliases:
          - gitea-act-runner.svc.local
    volumes:
      - ${STACK_DATA_ROOT}/act_runner:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      TZ: "Europe/Berlin"
      GITEA_INSTANCE_URL: 'http://gitea_service:3000'
      GITEA_INSTANCE_INSECURE: 'true'
      GITEA_RUNNER_REGISTRATION_TOKEN_FILE: /data/token.txt
      GITEA_RUNNER_NAME: 'local'
      GITEA_RUNNER_UID: 1000
      GITEA_RUNNER_GID: 1000
      GITEA_RUNNER_JOB_CONTAINER_NETWORK: swarm_net
      GITEA_RUNNER_MAX_PARALLEL_JOBS: 2
      ACT_CACHE_SERVER_HOST: gitea-act-runner.svc.local
```
