### ISSUE TITLE
mkdir: cannot create directory '/data/cache': Permission denied

### ISSUE THREAD

**Issue by spamnick** [vegardit/docker-gitea-act-runner#25]
```
  gitea_act_runner:
    container_name: gitea_runner
    image: vegardit/gitea-act-runner:latest
   
    depends_on:
      - gitea
   
    restart: unless-stopped
    networks:
      - my-network
    environment:
      TZ: "Europe/PARIS"
      GITEA_RUNNER_GID: 1000
      GITEA_RUNNER_UID: 1000
      GITEA_INSTANCE_URL: http://MY_GITEA:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: gtmgU4jwz8DcS9AdkwJuGPDgjAcBbk7Xfpt7ZevI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/nick/home-gitea-runner:/data:rw
```
Error:
```
gitea_runner  | mkdir: cannot create directory '/data/cache': Permission denied
gitea_runner  | 06:43:29 Error - exited with status 1 in [/opt/run_runner.sh] at line 29:
gitea_runner  |     26	#################################################
gitea_runner  |     27	# workaround for actions cache dir not being fully configurable
gitea_runner  |     28	# https://gitea.com/gitea/act/src/commit/62abf4fe116865f6edf85d6bce822050dd01ac78/pkg/runner/run_context.go#L360-L371
gitea_runner  |     29	mkdir -p $GITEA_RUNNER_ACTION_CACHE_DIR
gitea_runner  |     30	mkdir -p /tmp/.cache
gitea_runner  |     31	ln -sfn $GITEA_RUNNER_ACTION_CACHE_DIR /tmp/.cache/act
gitea_runner  |     32	export XDG_CACHE_HOME=/tmp/.cache
```
