### ISSUE TITLE
Job can not be completed : "no such table: action_task_output"

### ISSUE THREAD

**Issue by spamnick** [vegardit/docker-gitea-act-runner#26]
https://i.imgur.com/AXNWLiR.png

In logs:
```
gitea             | 2023/08/14 08:50:49 ...ons/runner/runner.go:148:UpdateTask() [W] Failed to find the sent outputs of task 40: no such table: action_task_output
gitea             | 2023/08/14 08:50:49 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/UpdateTask for 178.124.218.111:57006, 200 OK in 25.8ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea             | 2023/08/14 08:50:49 ...eb/routing/logger.go:102:func1() [I] router: completed POST /nick/MyProject/actions/runs/23/artifacts for 127.0.0.1:0, 200 OK in 27.9ms @ actions/view.go:435(actions.ArtifactsView)
gitea             | 2023/08/14 08:50:49 ...eb/routing/logger.go:102:func1() [I] router: completed POST /nick/MyProject/actions/runs/23/jobs/0 for 127.0.0.1:0, 200 OK in 28.9ms @ actions/view.go:121(actions.ViewPost)
gitea             | 2023/08/14 08:50:50 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/UpdateLog for 178.124.218.111:57006, 200 OK in 48.2ms @ <autogen
```
yaml:
```
#file: noinspection YAMLSchemaValidation
name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}

    - name: Setup JDK
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: amyu/setup-android@v2
      with:
        # default: false
        # Whether to use the cache
        cache-disabled: true

        # default: '30'
        # sdk version
        # see https://developer.android.com/studio/releases/platforms
        # It will always be installed.
        sdk-version: '30'

        # default: '30.0.3'
        # build tools version
        # see https://developer.android.com/studio/releases/build-tools
        # It will always be installed.
        build-tools-version: '30.0.3'

    - name: Build debug apk
      uses: gradle/gradle-build-action@v2.7.0
      with:
        arguments: --stacktrace -Dtrace :app:assembleDebug

```
