### ISSUE TITLE
Registration Error in setup of the act_runner in Docker-in-Docker approach

### ISSUE THREAD

**Issue by letalboy** [vegardit/docker-gitea-act-runner#47]
Hello, I'm trying to set up `act_runner` to be able to execute actions in my Gitea, I've tried a couple of method in last days, however without too much success, this seems to be a good project, and I'm trying to use it, however I'm getting this error:

```
gitea-runner-1      | level=info msg="Registering runner, arch=amd64, os=linux, version=v0.2.6."
gitea-runner-1      | level=warning msg="Runner in user-mode."
gitea-runner-1      | level=debug msg="Successfully pinged the Gitea instance server"
gitea-runner-1      | level=error msg="poller: cannot register new runner" error="unknown: runner token has already been activated"
gitea-runner-1      | Error: Failed to register runner: unknown: runner token has already been activated
```

For this config:

```
version: '3.8' # https://docs.docker.com/compose/compose-file/compose-versioning/

services:

  gitea_act_runner:
    container_name: gitea-runner-1
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: always
    volumes:
      - ./data:/data:rw # the config file is located at /data/.runner and needs to survive container restarts
    environment:
      # config parameters for initial runner registration:
      GITEA_INSTANCE_URL: '<my-url>' # required
      GITEA_RUNNER_REGISTRATION_TOKEN: '<my-token>'
      GITEA_RUNNER_NAME: "Runner1"
```

In the docker file i only have:

```
# Base image
FROM vegardit/gitea-act-runner:dind-latest
```

And the token used was fresh in every run, so I think it may be a problem related to the fact that the token isn't in a file or something like that, how should I config my token file and where it needs to be? 

This problem can be due to other things?

**Comment by letalboy** [comment]
Using this: 

```
docker run \
    -e GITEA_INSTANCE_URL=<my-gitea-address> \
    -e GITEA_RUNNER_REGISTRATION_TOKEN=<my-token> \
    --name gitea_act_runner \
    --privileged \
    vegardit/gitea-act-runner:dind-latest
```

Directly works and the act_runner connects successfully in the gitea aplication

**Comment by letalboy** [comment]
I tried using it directly like that: `image: vegardit/gitea-act-runner:dind-latest` but don't work, so I put it inside the Docker file. But your assumption related to it be initializing multiple times high be correct, since I saw the runner symbols change colors. I find an error saying that the volume where it stores persistence data isn't accessible because issues with permission, I tried to make it have permission but don't work, what I did was make it run directly with docker online command it makes it works.

I suspect that the issue is related to some permission when creating the volume when using docker-compose that causes a crash and makes the act to restart itself, at this point it probably already have accessed with the token making it invalid for future attempts causing token error. However, I can't get the full log anymore because I configured all the server to run with the one that is working, and I suspect that if I somehow try to connect it again can cause mess the docker pool…

Can you tell me what is the correct config for the volume and if I need to set any permissions to this dir?

**Comment by sebthom** [comment]
> I tried using it directly like that: `image: vegardit/gitea-act-runner:dind-latest` but don't work

what is happening when you do this?

**Comment by letalboy** [comment]
In the first try an image error happens saying that can't fetch the image, almost if it was trying to find it locally somehow, then the Dockerfile method make it works. But it wasn't supposed to be the same image anyway?

**Comment by sebthom** [comment]
I cannot reproduce the issue. It is working fine for me using this yaml:

```yaml
version: "3"

services:
  runner1:
    image: vegardit/gitea-act-runner:dind-latest
    privileged: true
    container_name: gitea_runner
    environment:
      GITEA_INSTANCE_URL: "https://the-gitea-instance/"
      GITEA_RUNNER_REGISTRATION_TOKEN: "THE_TOKEN"
      GITEA_RUNNER_NAME: "runner1"
    volumes:
      - gitea_data:/data
volumes:
  gitea_data:
```
