### ISSUE TITLE
error when run setup-qemu-action@v3 in gitea-act-runner:0.2.8.

### ISSUE THREAD

**Issue by kennazeng** [vegardit/docker-gitea-act-runner#50]
error when run in gitea-act-runner:0.2.8.

OS： Debain 11.8
Docker version 20.10.5+dfsg1, build 55c4c88
Gitea: 1.21.10

command line:
```sh
sudo docker run
  -v /data/gitea/runner:/data 
  -v /var/run/docker.sock:/var/run/docker.sock:rw
  -e GITEA_INSTANCE_URL=https://code.xxx.com 
  -e GITEA_RUNNER_REGISTRATION_TOKEN=xxxxxx
  -e GITEA_RUNNER_NAME=runner-1 
  -e GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:16-bullseye     
  -p 7705:7705
  --name runner-1 
  -d 
  vegardit/gitea-act-runner:0.2.8
```

Pipeline script:

```yaml
name: Passport Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [ '1.22' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: subdir/go.sum
      - name: Display Go version
        run: go version
      - name: Build
        run: make build
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
```

error message:

::group::Docker info
::endgroup::
::error::Unable to locate executable file: docker. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
