### ISSUE TITLE
setup-qemu (version 2 and 3) fails to see binfmt_misc path

### ISSUE THREAD

**Issue by evanrich** [vegardit/docker-gitea-act-runner#51]
```
[command]/usr/bin/docker run --rm --privileged tonistiigi/binfmt:latest --install all
error: no such device
cannot mount binfmt_misc filesystem at /proc/sys/fs/binfmt_misc
main.run
	/src/cmd/binfmt/main.go:183
main.main
	/src/cmd/binfmt/main.go:170
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571
::endgroup::
::group::Extracting available platforms
::endgroup::
::error::Unexpected end of JSON input
```

i can see that it's there in the runner:
```
act@act-runner-1:/proc/sys/fs$ ls -al
total 0
dr-xr-xr-x 1 root root 0 Apr  6 14:27 .
dr-xr-xr-x 1 root root 0 Apr  6 14:27 ..
-rw-r--r-- 1 root root 0 Apr  6 14:39 aio-max-nr
-r--r--r-- 1 root root 0 Apr  6 14:39 aio-nr
dr-xr-xr-x 2 root root 0 Apr  6 14:39 binfmt_misc
-r--r--r-- 1 root root 0 Apr  6 14:39 dentry-state
```

using the following pipeline:
```
jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.PULL_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*Dashboard/.*
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: | 
            image:latest
```

**Comment by evanrich** [comment]
Oh I forgot, here's the relevant part of my deployment:
```
defaultPodOptions:
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: Unconfined  
controllers:
  gitea:
    type: statefulset
    replicas: 2
    statefulset:
      volumeClaimTemplates:
        - name: cache
          globalMounts:
            - path: /data
          accessMode: ReadWriteOnce
          size: 10Gi
    containers:
      gitea:
        image:
          repository: vegardit/gitea-act-runner
          pullPolicy: IfNotPresent
          tag: dind-0.2.9
        securityContext:
          #runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          privileged: true
          seccompProfile:
            type: Unconfined
```

I'm using a generic helm chart to deploy the runner as a statefulset
