### ISSUE TITLE
Building docker image for multiplatform

### ISSUE THREAD

**Issue by jonneolie** [vegardit/docker-gitea-act-runner#68]
Hi,
I'm trying to build a docker image with this runner, but I am unable to build it for multiple platforms.

My gitea workflow file:
```
name: example.com website
run-name: ${{ gitea.actor }} example.com-website-code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: gitea.example.com
          username: ${{ secrets.BOT_USER }}
          password: ${{ secrets.BOT_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64/v8,linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gitea.example.com/websites/example.com:${{ gitea.run_id }}
            gitea.example.com/websites/example.com:latest
```

I added _platforms: linux/arm64/v8,linux/amd64_ here, to see if that works, but in gitea I'm getting the following error:
```
[command]/usr/bin/docker buildx build --file ./Dockerfile --iidfile /tmp/docker-actions-toolkit-XgjK1B/build-iidfile-07cae3fb80.txt --platform linux/arm64/v8,linux/amd64 --tag gitea.example.com/websites/example.com:79 --tag gitea.example.com/websites/example.com:latest --metadata-file /tmp/docker-actions-toolkit-XgjK1B/build-metadata-8a884b0854.json --push .
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
::error::buildx failed with: Learn more at https://docs.docker.com/go/build-multi-platform/

```
Is there any way to make it work for multi platforms?

**Comment by jonneolie** [comment]
I fixed it. It looks like I messed it up :)
I have added the "setup-buildx-action@v3" and change the build-push-action to v6.

```
name: example.com website
run-name: ${{ gitea.actor }} example.com-website-code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: gitea.example.com
          username: ${{ secretsWEBSITES_BOT_USER }}
          password: ${{ secrets.WEBSITES_BOT_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gitea.example.com/websites/example.com:${{ gitea.run_id }}
            gitea.example.com/websites/example.com:latest
```
