### ISSUE TITLE
GITEA_RUNNER_JOB_CONTAINER_OPTIONS causes network a issue

### ISSUE THREAD

**Issue by Yedrimas** [vegardit/docker-gitea-act-runner#7]
Using image : `vegardit/gitea-act-runner:dind-latest`
And compose : 
```yaml
  gitearunner:
    container_name: runner1
    image: vegardit/gitea-act-runner:dind-latest
    depends_on:
      - gitea
    privileged: true
    restart: unless-stopped
    networks:
      gitea-external:
      gitea-internal:
    environment:
      GITEA_RUNNER_JOB_CONTAINER_OPTIONS: --add-host=gitea:172.0.1.5  --volume /repo:/repo
      GITEA_RUNNER_JOB_CONTAINER_PRIVILEGED: true
      TZ: Europe/PARIS
      GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: [very secret token]
    volumes:
      - /gitea/runner1:/data:rw
      - /etc/repo:/repo
```

The latest update causes the `Set up job` in Gitea to fail with : `Error response from daemon: container sharing network namespace with another container or host cannot be connected to any other network`
When removing the `GITEA_RUNNER_JOB_CONTAINER_OPTIONS` or setting it to empty; the issue vanishes.
I've tried modifying the content of the variable to only mount the volume or the --add-host, but the issue is still present.

This was not the case in previous version(s) of this image.
_(Don't mind the weird, --add-host value)_
