### ISSUE TITLE
There is a timeout error during the build. (kuber config)

### ISSUE THREAD

**Issue by kislenko-artem** [vegardit/docker-gitea-act-runner#71]
When I used `vegardit/gitea-act-runner:dind-latest` or `vegardit/gitea-act-runner:dind-rootless-latest`, runner get timeout error.
When I started using `gitea/act_runner:0.2.10-dind-rootless` problems dissapeared,

Building for my python program (same problem, when I builded fronted - building can't get debian packages)

```
#9 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
------
 > [5/8] RUN pip install -r requirements.txt:
18.51 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
34.10 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
50.23 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
67.33 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
86.43 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/aiofiles/
101.5 ERROR: Could not find a version that satisfies the requirement aiofiles (from versions: none)
106.7 ERROR: No matching distribution found for aiofiles
------
Dockerfile:5
--------------------
   3 |     RUN apt install -y libmagic1
   4 |     COPY requirements.txt .
   5 | >>> RUN pip install -r requirements.txt
   6 |     COPY . .
   7 |     ENV PYTHONPATH=/app
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
::error::buildx failed with: ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 
```

Config example:
P.S. variables `GITEA_RUNNER_JOB_CONTAINER_PRIVILEGED` `GITEA_RUNNER_JOB_CONTAINER_NETWORK` - there was different firstly I tried without its.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: act-runner-vol
  namespace: gitea-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: act-runner
  name: act-runner
  namespace: gitea-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-runner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: act-runner
    spec:
      restartPolicy: Always
      volumes:
      - name: runner-data
        persistentVolumeClaim:
          claimName: act-runner-vol
      containers:
      - name: runner
        image: vegardit/gitea-act-runner:dind-latest
        env:
        - name: GITEA_RUNNER_LOG_LEVEL
          value: debug
        - name: GITEA_RUNNER_JOB_CONTAINER_PRIVILEGED
          value: "true" 
        - name: GITEA_RUNNER_JOB_CONTAINER_NETWORK
          value: host
        - name: GITEA_INSTANCE_URL
          value: ""
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          value: ""
        - name: GITEA_RUNNER_LABELS
          value: ""
        securityContext:
          privileged: true
        volumeMounts:
        - name: runner-data
          mountPath: /data

```
