### ISSUE TITLE
New network for each job

### ISSUE THREAD

**Issue by DarkWingMcQuack** [vegardit/docker-gitea-act-runner#73]
Hey, i have a workflow which looks like this:

```yml
name: Cache Fuzzing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  user-cache-fuzzing:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    ....

  address-cache-fuzzing:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    ....
```

this is my act runner config:

```yml
services:
  gitea-runner:
    image: vegardit/gitea-act-runner:dind-latest
    privileged: true
    container_name: "gitea-runner"
    environment:
      TZ: "Europe/Berlin"
      GITEA_INSTANCE_URL: "<url>"
      GITEA_RUNNER_REGISTRATION_TOKEN: '<token>'
      GITEA_RUNNER_NAME: "gitea-runner"
      GITEA_RUNNER_MAX_PARALLEL_JOBS: 6
      ACT_CACHE_SERVER_ENABLED: true
      ACT_CACHE_SERVER_DIR: "/data/cache"
    volumes:
      - "runner-data:/data:rw"

volumes:
  runner-data:
```

problem is that if both jobs run in parallel the both redis services try to bind to the same port and one of them fails.
how can i ensure that the both jobs run in their own network?
